### ISSUE TITLE
Change username_template to bind_dn

### ISSUE THREAD

**Issue by ryanlovett** [yuvipanda/ldapauthenticator#4]
Not a big deal, but what you've got as the username_template (6) is typically called the bind_dn (half dozen) in most LDAP configurations.

Thanks for this authenticator btw!

**Comment by yuvipanda** [comment]
Thanks for opening issue :D 

I agree that username_template seems wrong, and bind_dn is probably a better name. Am wondering if it should be bind_dn or bind_dn_template (since I guess you derive the actual bind_dn from it?). Better to change it now rather than later after more users are using it :)

**Comment by ryanlovett** [comment]
+1 bind_dn_template

**Comment by yuvipanda** [comment]
@ryanlovett can you take a look at the PR and maybe give it a +1? :)
